"""Functional diffusion generative model for functional data."""

import warnings
from pathlib import Path
from typing import cast

import numpy as np
import torch
from sklearn.utils.validation import check_is_fitted
from torch import Tensor
from torch.utils.data import DataLoader, Dataset, TensorDataset

from ..._utils._sklearn_adapter import BaseEstimator
from ...representation.grid import FDataGrid
from ...typing._numpy import NDArrayFloat
from .diffusion_process import (
    ForwardDiffusionProcess,
    VariancePreservingDiffusionProcess,
)
from .reverse_diffusion import (
    EulerMaruyamaIntegrator,
    ReverseDiffusionProcess,
    SDEReverseDiffusionProcess,
)
from .score_model import ScoreModel, UNetScoreModel
from .torch_random_numbers import make_torch_rng

BatchType = tuple[Tensor, Tensor] | tuple[Tensor]


def _build_default_score_model(
    n_points: int,
    diff_process: ForwardDiffusionProcess,
    device: torch.device | str,
    seed: int | None = None,
) -> ScoreModel:
    """Build the default UNetScoreModel for the given diffusion process.

    Args:
        n_points: Number of discretization points in the functional data.
        diff_process: The forward diffusion process, used to configure
            ``multiply_inv_sigma`` on the score model.
        device: The device on which the score model will be trained and
            used for generation.
        seed: Random seed for reproducibility.  Defaults to ``None``.

    Returns:
        An instance of :class:`UNetScoreModel` configured for
        ``diff_process``.
    """
    is_cuda = str(device).startswith("cuda")
    devices = [device] if is_cuda else []
    if seed is not None:
        with torch.random.fork_rng(devices=devices):
            torch.manual_seed(seed)
            if is_cuda:
                torch.cuda.manual_seed_all(seed)
            model = UNetScoreModel(
                n_points=n_points,
                multiply_inv_sigma=diff_process.multiply_inv_sigma,
                device=device,
            )
    else:
        model = UNetScoreModel(
            n_points=n_points,
            multiply_inv_sigma=diff_process.multiply_inv_sigma,
            device=device,
        )
    return model


class FunctionalDiffusionGenerator(BaseEstimator):
    r"""Score-based diffusion model for generating functional data.

    This class implements a score-based generative model adapted for
    functional data.  The model learns the score function of the data
    distribution by training a neural network :math:`s_\theta` on a
    denoising score-matching objective.

    **Forward process.** Given a clean functional datum
    :math:`\mathbf{x}_0`, the forward diffusion process corrupts it by
    adding Gaussian noise following the transition kernel

    .. math::

        q(\mathbf{x}_t \mid \mathbf{x}_0)
        = \mathcal{N}\!\left(\mathbf{x}_t;\, \mu_t(\mathbf{x}_0),\,
        \sigma_t^2 \mathbf{I}\right),

    where the functions :math:`\mu_t` and :math:`\sigma_t` are defined
    by the chosen
    :class:`~skfda.ml.generative.diffusion_process.ForwardDiffusionProcess`.

    **Training objective.** The score network is trained to minimise the
    denoising score-matching loss

    .. math::

        \mathcal{L}(\theta) = \mathbb{E}_{t,\, \mathbf{x}_0,\, \mathbf{z}}
        \left[\left\| \sigma_t \, s_\theta(\mathbf{x}_t, t)
        + \mathbf{z} \right\|^2\right],

    where :math:`\mathbf{x}_t = \mu_t(\mathbf{x}_0) + \sigma_t \mathbf{z}`
    and :math:`\mathbf{z} \sim \mathcal{N}(\mathbf{0}, \mathbf{I})`.

    **Reverse process.** New samples are generated by starting from noise
    :math:`\mathbf{x}_T \sim p_T` and running the reverse SDE backwards
    in time using the learnt score :math:`s_\theta`.

    .. note::

        Only univariate (``dim_domain=1``, ``dim_codomain=1``) functional
        data is currently supported.

    Parameters:
        diff_process: Forward diffusion process that defines
            :math:`\mu_t` and :math:`\sigma_t`.  Defaults to
            :class:`~skfda.ml.generative.diffusion_process.VariancePreservingDiffusionProcess`.
        score_model: Pre-built score network.  Must implement
            ``forward(x, t, y=None)`` and return a tensor with the same
            shape as ``x``.  If ``None``, a default
            :class:`~skfda.ml.generative.score_model.UNetScoreModel`
            is constructed during :meth:`fit`.
        normalize: Normalize training data to :math:`[-1, 1]` before
            fitting.  Mutually exclusive with ``standardize``.
            Defaults to ``True``.
        standardize: Standardize training data to zero mean and unit
            pointwise variance before fitting.  Mutually exclusive with
            ``normalize``.  Defaults to ``False``.
        max_iter: Number of training epochs.  Defaults to ``200``.
        batch_size: Mini-batch size for the data loader.
            Defaults to ``32``.
        n_jobs: Number of worker processes for
            :class:`torch.utils.data.DataLoader`.  ``0`` uses the main
            process. Defaults to ``0``.
        device: Computation device for training and generation
            (e.g. ``"cpu"`` or ``"cuda"``).  Defaults to ``"cpu"``.
        seed: Random seed for reproducibility.  Defaults to ``None``.

    Attributes:
        score_model\_: Trained score network (available after
            :meth:`fit`).
        grid_points\_: Discretization grid of the training data
            (available after :meth:`fit`).
        _bias\_: Bias used to invert the preprocessing transformation
            (available after :meth:`fit`).
        _scale\_: Scale used to invert the preprocessing transformation
            (available after :meth:`fit`).

    Examples:
        Fit a generator on Gaussian process trajectories and draw new
        samples:

        >>> from skfda.datasets import make_gaussian_process
        >>> from skfda.ml.generative.diffusion_model import (
        ...     FunctionalDiffusionGenerator,
        ... )
        >>> X = make_gaussian_process(
        ...     n_samples=30, n_features=64, seed=0,
        ... )
        >>> gen = FunctionalDiffusionGenerator(max_iter=5, seed=0)
        >>> _ = gen.fit(X)  # doctest: +SKIP
        >>> X_gen = gen.generate(n_samples=5)  # doctest: +SKIP
        >>> X_gen.n_samples  # doctest: +SKIP
        5

    """
    _CHECKPOINT_VERSION: int = 1
    def __init__(  # noqa: PLR0913 # Ignore too-many arguments
        self,
        diff_process: ForwardDiffusionProcess | None = None,
        score_model: ScoreModel | None = None,
        *,
        normalize: bool = True,
        standardize: bool = False,
        max_iter: int = 200,
        batch_size: int = 32,
        n_jobs: int = 0,
        device: torch.device | str = "cpu",
        seed: int | None = None,
    ) -> None:
        super().__init__()
        self.diff_process = (
            diff_process
            if diff_process is not None
            else VariancePreservingDiffusionProcess()
        )
        self.score_model = score_model
        self.normalize = normalize
        self.standardize = standardize

        if self.normalize and self.standardize:
            msg = "normalize and standardize cannot both be True."
            raise ValueError(msg)

        self.max_iter = max_iter
        self.n_jobs = n_jobs
        self.device = device
        self.batch_size = batch_size
        self.seed = seed


    def _release_score_model(self) -> None:
        """Move an existing score model off CUDA before replacing it."""
        if hasattr(self, "score_model_"):
            self.score_model_.cpu()  # free VRAM; GC handles CPU RAM

    def _build_or_get_score_model(
        self, n_points: int, seed: int | None = None,
    ) -> ScoreModel:
        """Create a score model using the current estimator configuration."""
        if self.score_model is not None:
            if not isinstance(self.score_model, torch.nn.Module):
                msg = "score_model must be a torch.nn.Module or None."
                raise TypeError(msg)
            return self.score_model.to(self.device)

        return _build_default_score_model(
            n_points=n_points,
            diff_process=self.diff_process,
            device=self.device,
            seed=seed,
        )

    def _validate_score_model_output(
        self,
        x: Tensor,
        t: Tensor,
        y: Tensor | None = None,
    ) -> None:
        """Validate score model compatibility using a lightweight dry run."""
        out = self.score_model_(x, t, y)

        if not isinstance(out, Tensor):
            msg = "score_model must return a torch.Tensor."
            raise TypeError(msg)

        if out.shape != x.shape:
            msg = (
                "score_model output shape must match input x shape "
                f"({tuple(x.shape)}), got {tuple(out.shape)}."
            )
            raise ValueError(
                msg,
            )

    def fit(
        self,
        X: FDataGrid,
        y: NDArrayFloat | None = None,
    ) -> "FunctionalDiffusionGenerator":
        r"""Fit the diffusion model to the training functional data.

        The score network :math:`s_\theta` is trained to minimise the
        denoising score-matching loss.  After fitting, the model can be
        used to generate new samples via :meth:`generate`.

        The number of training epochs and the batch size are controlled
        by the ``max_iter`` and ``batch_size`` constructor parameters,
        respectively.

        Args:
            X: Training functional data.  Must be a univariate
                (``dim_domain=1``, ``dim_codomain=1``)
                :class:`~skfda.representation.FDataGrid`.
            y: Class labels for each sample.  When provided, the score
                model receives the labels and can learn a
                class-conditional distribution.  Defaults to ``None``.

        Returns:
            The fitted estimator (``self``), following the scikit-learn
            convention.

        Raises:
            ValueError: If ``X`` is not a univariate functional object
                (``dim_domain != 1`` or ``dim_codomain != 1``).
            ValueError: If the score model has no trainable parameters.
            TypeError: If a custom ``score_model`` is not a
                :class:`torch.nn.Module`.

        Examples:
            Fit a generator on Gaussian process trajectories:

            >>> from skfda.datasets import make_gaussian_process
            >>> from skfda.ml.generative.diffusion_model import (
            ...     FunctionalDiffusionGenerator,
            ... )
            >>> X = make_gaussian_process(
            ...     n_samples=30, n_features=64, random_state=0,
            ... )
            >>> gen = FunctionalDiffusionGenerator(max_iter=5, seed=0)
            >>> gen.fit(X)  # doctest: +SKIP
            FunctionalDiffusionGenerator(max_iter=5, seed=0)
            >>> hasattr(gen, "score_model_")  # doctest: +SKIP
            True

        """
        if X.dim_domain != 1 or X.dim_codomain != 1:
            msg = (
                "FunctionalDiffusionGenerator only supports"
                " 1D functional data."
            )
            raise ValueError(msg)
        self.grid_points_ = X.grid_points[0]
        grid_size = len(self.grid_points_)

        self.score_model_ = self._build_or_get_score_model(
            n_points=grid_size, seed=self.seed,
        )

        params = list(self.score_model_.parameters())
        if not params:
            msg = "score_model must define at least one trainable parameter."
            raise ValueError(
                msg,
            )

        self.score_model_.train()

        # Independent generators for DataLoader shuffle and training loop.
        loader_seed = self.seed
        train_seed  = None if self.seed is None else self.seed + 1
        loader_generator = make_torch_rng(loader_seed, device="cpu")
        train_generator = make_torch_rng(train_seed, device=self.device)

        dataset = self._preprocess(X, y)

        data_loader: DataLoader[BatchType] = DataLoader(
                    dataset,
                    batch_size=self.batch_size,
                    shuffle=True,
                    num_workers=self.n_jobs,
                    generator=loader_generator,
                )
        # Fit on the FULL dataset, not just one batch
        # This is always true for the current implementation,
        # but we keep it outside the loop in case of future changes.
        assert isinstance(dataset, TensorDataset)
        x_all = dataset.tensors[0].to(self.device)
        self.diff_process.fit(x_all)

        # For the dry-run validation, a single slice is enough
        x_val = x_all[:self.batch_size]
        t_val = torch.full((x_val.shape[0],), 0.5, device=self.device)
        y_val = (
            dataset.tensors[1].to(self.device)[:self.batch_size]
            if len(dataset.tensors) > 1
            else None
        )
        self._validate_score_model_output(x_val, t_val, y_val)


        learning_rate = 1e-3
        optimizer = torch.optim.Adam(
            self.score_model_.parameters(),
            lr=learning_rate,
        )

        eps = 1e-3  # lower bound on t; score estimates are unreliable near t=0
        epoch_iter = range(self.max_iter)

        for _ in epoch_iter:
            for data in data_loader:
                if len(data) == 2:  # noqa: PLR2004 # Ignore magic value
                    x, y = data
                    x = x.to(self.device)
                    # cast y to avoid mypy error
                    # mypy cannot infer that the second tensor is y
                    y_tensor = cast("Tensor", y).to(self.device)
                else:
                    x = data[0].to(self.device)
                    y_tensor = None

                t = (
                    torch.rand(
                        x.shape[0],
                        device=self.device,
                        generator=train_generator,
                    ) * (self.diff_process.T - eps)
                ) + eps

                loss = self._loss_function(
                    self.score_model_, x, t, y_tensor, train_generator,
                )
                optimizer.zero_grad()
                loss.backward() # type: ignore[no-untyped-call]

                torch.nn.utils.clip_grad_norm_(
                    self.score_model_.parameters(),
                    max_norm=1.0,
                )

                optimizer.step()

        self.score_model_.eval()
        return self

    def _preprocess(
            self,
            X: FDataGrid,
            y: NDArrayFloat | None = None,
    ) -> Dataset[BatchType] :
        """Preprocesses the functional data before training or sampling.

        Args:
            X: The input functional data as an FDataGrid object.
            y: Optional tensor with the class labels of the data.
                Default is `None`.

        Returns:
            A TorchDataset with the preprocessed data.
        """
        eps = 1e-2
        self._bias_ = 0.0
        self._scale_ = 1.0

        if self.normalize:
            max_fd = X.data_matrix.max()
            min_fd = X.data_matrix.min()
            self._bias_ = (max_fd + min_fd) / 2
            self._scale_ = ((max_fd - min_fd) / 2)
        elif self.standardize:
            mean_fd = X.data_matrix.mean()
            std_fd = X.data_matrix.std()
            self._bias_ = mean_fd
            self._scale_ = std_fd
        if self._scale_ < eps:
            self._scale_ = 1.0

        x_scaled = (X - self._bias_) / self._scale_
        return _fdatagrid_to_tensor_dataset(x_scaled, y)

    def _loss_function(
            self,
            score_model: torch.nn.Module,
            x: Tensor,
            t: Tensor,
            y: Tensor | None,
            generator: torch.Generator,
    ) -> Tensor:
        r"""Compute the denoising score-matching loss for one mini-batch.

        .. math::

            \mathcal{L}(\theta) = \mathbb{E}_{t,\,x_0,\,z}\!\left[
            \left\|\sigma_t\,s_\theta(x_t,\,t) + z\right\|^2\right],

        where :math:`x_t = \mu_t(x_0) + \sigma_t z` and
        :math:`z \sim \mathcal{N}(\mathbf{0}, \mathbf{I})`.

        Args:
            score_model: The score network :math:`s_\theta`.
            x: Clean functional data, shape (N, M) or (N, 1, M).
            t: Per-sample diffusion times, shape (N,).
            y: Optional class labels, shape (N,). ``None`` for unconditional.
            generator: RNG for the noise sample :math:`z`.

        Returns:
            Scalar loss tensor.
        """
        mu_t = self.diff_process.mean_cond(x, t)
        z = torch.randn(
            x.shape,
            device=x.device,
            dtype=x.dtype,
            generator=generator,
        )
        score_time_z = self.diff_process.multiply_sigma(z, t)
        x_t = mu_t + score_time_z
        score = score_model(x_t, t, y)
        score_time_sigma = self.diff_process.multiply_sigma(score, t)

        return torch.mean(
            torch.sum(
                (score_time_sigma + z) ** 2,
                dim=1,
            ),
        )

    def generate(
            self,
            n_samples: int,
            reverse_process: ReverseDiffusionProcess | None = None,
            y: NDArrayFloat | None = None,
    ) -> FDataGrid:
        r"""Generate new functional data samples from the fitted model.

        Starts from samples drawn from the limit distribution
        :math:`p_T` of the forward process and applies the reverse
        diffusion process to obtain new realisations of the learnt data
        distribution.

        If ``y`` is provided the number of generated samples equals
        ``len(y)`` and the score model is conditioned on the supplied
        labels (requires that the model was fitted with labels) and
        the `ScoreModel` needs to accept the labels as input.

        Args:
            n_samples: Number of samples to generate.  Ignored when
                ``y`` is provided.
            reverse_process: Reverse-time solver used to denoise the
                initial noise back to data space.  If ``None``, a
                :class:`~skfda.ml.generative.reverse_diffusion.SDEReverseDiffusionProcess`
                with an Euler-Maruyama integrator
                :class:`~skfda.ml.generative.integrators.EulerMaruyamaIntegrator`
                is used.
            y: Class labels for conditional generation.  Must match the
                label encoding used during :meth:`fit`.  Defaults to
                ``None``.

        Returns:
            :class:`~skfda.representation.FDataGrid` containing the
            generated functional data, discretized on the same grid as
            the training data.

        Raises:
            sklearn.exceptions.NotFittedError: If the model has not been
                fitted yet (i.e. :meth:`fit` has not been called).

        Examples:
            Generate unconditional samples after fitting:

            >>> from skfda.datasets import make_gaussian_process
            >>> from skfda.ml.generative.diffusion_model import (
            ...     FunctionalDiffusionGenerator,
            ... )
            >>> X = make_gaussian_process(
            ...     n_samples=30, n_features=64, random_state=0,
            ... )
            >>> gen = FunctionalDiffusionGenerator(max_iter=5, seed=0)
            >>> _ = gen.fit(X)  # doctest: +SKIP
            >>> X_gen = gen.generate(n_samples=10)  # doctest: +SKIP
            >>> X_gen.n_samples  # doctest: +SKIP
            10
            >>> X_gen.dim_domain, X_gen.dim_codomain  # doctest: +SKIP
            (1, 1)

        """
        check_is_fitted(self, attributes=["score_model_", "grid_points_"])

        if reverse_process is None:
            reverse_process = SDEReverseDiffusionProcess(
                EulerMaruyamaIntegrator(
                    seed=self.seed, device=self.device,
                ),
            )

        if y is not None:
            n_samples = len(y)
            y_torch = torch.as_tensor(y, device=self.device)
        else:
            y_torch = None
        # Sample from the limit distribution of the forward process.
        x_t = self.diff_process.sample_limit_distribution(
            n_samples,
            self.device,
        )
        # No gradients needed during generation; this avoids storing
        # the computation graph and significantly reduces memory usage.
        with torch.no_grad():
            x_0 = reverse_process.reverse(
                self.diff_process,
                score_model=self.score_model_,
                x_t=x_t,
                t_1=self.diff_process.T,
                y=y_torch,
            )


        data_matrix = x_0.detach().cpu().numpy().reshape(n_samples, -1, 1)

        f_data = FDataGrid(
            data_matrix=data_matrix,
            grid_points=self.grid_points_,
        )

        if self.normalize or self.standardize:
            bias = getattr(self, "_bias_", 0.0)
            scale = getattr(self, "_scale_", 1.0)
            f_data = f_data * scale + bias
        return f_data

    def generate_evolution(
        self,
        n_samples: int,
        timesteps: NDArrayFloat,
        reverse_process: ReverseDiffusionProcess | None = None,
        y: NDArrayFloat | None = None,
    ) -> list[FDataGrid]:
        """Generate the evolutionary trajectory of functional data samples.

        Tracks and returns the state of the generated functional data at each
        specified time step during the reverse diffusion process.

        If ``y`` is provided, the generated samples are conditioned on the
        supplied labels and ``n_samples`` is ignored.

        Args:
            n_samples: Number of samples to generate.  Ignored when ``y``
                is provided.
            timesteps: Array of time steps (usually descending from ``T``
                to ``0``) at which to capture the intermediate states.
            reverse_process: Reverse-time solver.  Defaults to
                ``SDEReverseDiffusionProcess`` with an Euler-Maruyama
                integrator when ``None``.
            y: Class labels for conditional generation.  Defaults to
                ``None``.

        Returns:
            A list of :class:`~skfda.representation.FDataGrid` objects,
            one per entry in ``timesteps``, representing the denoising
            trajectory.

        Raises:
            sklearn.exceptions.NotFittedError: If the model has not been
                fitted yet.
        """
        check_is_fitted(self, attributes=["score_model_", "grid_points_"])

        if reverse_process is None:
            reverse_process = SDEReverseDiffusionProcess(
                EulerMaruyamaIntegrator(
                    seed=self.seed, device=self.device,
                ),
            )

        if y is not None:
            n_samples = len(y)
            y_torch = torch.as_tensor(y, device=self.device)
        else:
            y_torch = None
        # Draw initial noise from the forward process limit distribution.
        x_current = self.diff_process.sample_limit_distribution(
            n_samples,
            self.device,
        )

        evolution_tensors = []

        # Reverse diffusion process piece-wise to capture intermediate samples
        with torch.no_grad():
            for i in range(len(timesteps) - 1):
                t_current = timesteps[i]
                t_next = timesteps[i + 1]

                # Store the state at the current timestep
                evolution_tensors.append(x_current.clone())
                x_current = reverse_process.reverse(
                    self.diff_process,
                    score_model=self.score_model_,
                    x_t=x_current,
                    t_1=t_current,
                    y=y_torch,
                    t_0=t_next,
                )

            # Append the final state (usually at t=0)
            evolution_tensors.append(x_current.clone())


        # Hoist preprocessing constants out of the per-sample loop.
        scaling = self.normalize or self.standardize
        bias = getattr(self, "_bias_", 0.0) if scaling else 0.0
        scale = getattr(self, "_scale_", 1.0) if scaling else 1.0

        f_data_evolution = []

        for x_step in evolution_tensors:
            data_matrix = (
                x_step.detach().cpu().numpy().reshape(n_samples, -1, 1)
            )

            f_data = FDataGrid(
                data_matrix=data_matrix,
                grid_points=self.grid_points_,
            )

            if self.normalize or self.standardize:
                f_data = f_data * scale + bias

            f_data_evolution.append(f_data)

        return f_data_evolution

    def save(self, path: str | Path) -> None:
        """Persist the fitted generator to disk using ``torch.save``.

        Stores the generator's configuration, preprocessing metadata,
        and the full checkpoints of both the diffusion process and the
        score model in a single file.  The file is written atomically:
        the data is first flushed to a temporary file in the same directory
        and then renamed, so a failed write never produces a corrupt
        checkpoint.

        Args:
            path: Destination path for the checkpoint file.

        Raises:
            sklearn.exceptions.NotFittedError: If the model has not been
                fitted yet.
            ValueError: If the diffusion process callables are not picklable
                (propagated from
                :meth:`ForwardDiffusionProcess.to_checkpoint`).

        .. warning::
            The checkpoint stores class references via pickle.  Only load
            checkpoints from trusted sources.
        """
        check_is_fitted(self, attributes=["score_model_", "grid_points_"])

        if self.seed is None:
            warnings.warn(
                "Saving a generator fitted with seed=None. "
                "Exact sample reproducibility after load is not guaranteed "
                "because the global numpy RNG state was used during training. "
                "Pass an integer seed for full reproducibility.",
                UserWarning,
                stacklevel=2,
            )

        checkpoint = {
            "version": self._CHECKPOINT_VERSION,
            # Generator init kwargs — enough to reconstruct the instance.
            # diff_process and score_model are stored as sub-checkpoints below.
            "normalize": self.normalize,
            "standardize": self.standardize,
            "max_iter": self.max_iter,
            "batch_size": self.batch_size,
            "n_jobs": self.n_jobs,
            "device": str(self.device),
            # Preprocessing metadata
            "grid_points": np.asarray(self.grid_points_).tolist(),
            "bias": float(getattr(self, "_bias_", 0.0)),
            "scale": float(getattr(self, "_scale_", 1.0)),
            # Component checkpoints
            "diff_process": self.diff_process.to_checkpoint(),
            "score_model": self.score_model_.to_checkpoint(),
            "seed": self.seed,
        }

        path = Path(path)
        # Save to a temporary file first, then rename to ensure atomicity.
        tmp_path = path.with_suffix(".tmp")
        try:
            torch.save(checkpoint, tmp_path)
            Path.replace(tmp_path, path)
        except Exception:
            tmp_path.unlink(missing_ok=True)
            raise


    @classmethod
    def load(
        cls,
        path: str | Path,
        device: torch.device | str | None = None,
        diff_process: ForwardDiffusionProcess | None = None,
    ) -> "FunctionalDiffusionGenerator":
        """Load a fitted generator from a checkpoint file.

        Reconstructs the generator and all its components from a file
        produced by :meth:`save`.  No prior configuration is required:
        the checkpoint is self-describing and the correct subclasses for
        both the diffusion process and the score model are restored
        automatically.

        Args:
            path: Path to the checkpoint file.
            device: Override the device stored in the checkpoint (e.g. load a
                GPU checkpoint on CPU).  If ``None``, the stored device is
                used.
            diff_process: Pre-built diffusion process instance to restore
                state into.  Required when the stored process has constructor
                arguments that are not picklable (e.g. a
                :class:`~skfda.ml.generative.DiagonalDiffusionProcess`
                built with lambda functions).  The type must match the class
                stored in the checkpoint exactly; the callables are taken from
                this instance while the fitted state (``M``, precomputed
                grids, etc.) is restored from the checkpoint.

        Returns:
            A fully reconstructed and fitted
            :class:`FunctionalDiffusionGenerator` ready to call
            :meth:`generate` on.

        Raises:
            ValueError: If the checkpoint format is invalid, required keys
                are missing, or the stored class types are mismatched.

        .. warning::
            This method calls ``torch.load`` with ``weights_only=False``
            because class references are stored in the checkpoint.  Only
            load checkpoints from trusted sources.
        """
        checkpoint = torch.load(
            Path(path),
            map_location="cpu",
            weights_only=False,
        )

        if not isinstance(checkpoint, dict):
            msg = "Invalid checkpoint format: expected a dictionary."
            raise TypeError(
                msg,
            )

        required_keys = {
            "version",
            "normalize", "standardize", "max_iter", "batch_size",
            "n_jobs", "device",
            "grid_points", "bias", "scale",
            "diff_process", "score_model",
            "seed",
        }
        missing_keys = required_keys - checkpoint.keys()
        if missing_keys:
            msg = (
                f"Checkpoint is missing required keys: {sorted(missing_keys)}."
            )
            raise ValueError(
                msg,
            )

        target_device = device if device is not None else checkpoint["device"]

        # Restore diffusion process.  If diff_process is provided, its
        # callables are used and only the fitted state is pulled from the
        # checkpoint (see ForwardDiffusionProcess.from_checkpoint).
        restored_diff_process = ForwardDiffusionProcess.from_checkpoint(
            checkpoint["diff_process"],
            instance=diff_process,
        )

        # Reconstruct the generator from the stored init kwargs.
        # diff_process and score_model are injected directly below.
        gen = cls(
            diff_process=restored_diff_process,
            normalize=checkpoint["normalize"],
            standardize=checkpoint["standardize"],
            max_iter=checkpoint["max_iter"],
            batch_size=checkpoint["batch_size"],
            n_jobs=checkpoint["n_jobs"],
            device=target_device,
            seed=checkpoint["seed"],
        )

        score_model = ScoreModel.from_checkpoint(checkpoint["score_model"])
        score_model.on_load(restored_diff_process)
        score_model = score_model.to(target_device)
        score_model.eval()
        gen._release_score_model()
        gen.score_model_ = score_model

        # Restore preprocessing metadata.
        gen.grid_points_ = np.asarray(checkpoint["grid_points"])
        gen._bias_ = float(checkpoint["bias"])
        gen._scale_ = float(checkpoint["scale"])

        return gen


def _fdatagrid_to_tensor_dataset(
    X: FDataGrid, y: NDArrayFloat | None = None,
) -> Dataset[BatchType]:
    r"""Converts an FDataGrid object to a PyTorch TensorDataset.

    The functional data must be a :math:`\mathbb{R}^1`-valued function.

    Args:
        X: The input functional data as an FDataGrid object.
        y: Optional tensor with the class labels of the data.
           Default is `None`.

    Returns:
        A PyTorch TensorDataset containing the functional data.
    """
    data_tensor = torch.from_numpy(X.data_matrix[..., 0]).float()
    if y is not None:
        labels_tensor = torch.from_numpy(y).float()
        dataset = TensorDataset(data_tensor, labels_tensor)
    else:
        dataset = TensorDataset(data_tensor)
    return cast("Dataset[BatchType]", dataset)

